"""Query intent data models."""
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ScenarioType(str, Enum):
    """Scenario types for mobility generation."""

    URBAN = "urban"
    SUBURBAN = "suburban"
    RURAL = "rural"
    HIGHWAY = "highway"
    MIXED = "mixed"


class MobilityClass(str, Enum):
    """Types of mobile entities."""

    STATIONARY = "stationary"
    PEDESTRIAN = "pedestrian"
    CYCLIST = "cyclist"
    CAR = "car"


class DistributionSource(str, Enum):
    """Source of UE distribution."""

    PARSED = "parsed"  # Extracted from user query
    PREDICTED = "predicted"  # Generated by LLM from context


class UEDistribution(BaseModel):
    """UE distribution with source tracking.

    The distribution values (stationary, pedestrian, cyclist, car) are stored
    directly at the top level alongside the source field.
    """

    stationary: float = Field(default=0.0, ge=0.0, le=1.0)
    pedestrian: float = Field(default=0.0, ge=0.0, le=1.0)
    cyclist: float = Field(default=0.0, ge=0.0, le=1.0)
    car: float = Field(default=0.0, ge=0.0, le=1.0)
    source: DistributionSource


class QueryIntent(BaseModel):
    """Structured representation of user's mobility intent."""

    scenario_type: ScenarioType
    location: str
    num_ues: int = Field(default=30, gt=0, le=10000)  # Default 30 UEs if not specified
    num_ticks: int = Field(default=50, gt=0)
    ue_distribution: Optional[UEDistribution] = None  # Now includes source tracking
    raw_query: str  # IMPORTANT: Used by Parameter Agent for distribution inference
